# Site settings
title: Sree Guru Astrology
email: astrologer@sreeguru.com
description: > # Wooho
  A wonderful site
baseurl: "/sree-guru-astrology/" # Path for github.io pages
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: dineshvasudevan
github_username:  dinks

# Build settings
markdown: kramdown
