# Site settings
title: Sree Guru Astrology
email: astrologer@sreeguru.com
description: > # Wooho
  Astrological Solution to a better life
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sreeguruastrology.com" # the base hostname & protocol for your site
twitter_username: dineshvasudevan
github_username:  dinks
contact_number: "+91 9447378660"
email: "sreeguruastrology@yahoo.com"

# Build settings
markdown: kramdown
